### ISSUE TITLE
Need to handle flagging bought items cause they aren't bring flagged

### ISSUE THREAD

**Issue by strenkml** [MidNoon/Reincarceration#4]

**Comment by MidNoon** [comment]
The previous method of performing this was to delay flagging with a scheduler being provided the type and quantity of items being bought. This would then identify the specified quantity of items in the player's inventory to be flagged and then perform the flagging on them. It wasn't a perfect solution but worked in previous testing. However, it's not a robust solution, and with the introduction of the listener on inventory close, it's even less reliable. I'm open to suggestions or thoughts on the best solution here.

**Comment by MidNoon** [comment]
fixed in version 1.0.3
